//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Market.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLPROPERTY
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> CATEGORY { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public string PHOTO { get; set; }
        public string DETAIL { get; set; }
    
        public virtual TBLCategory TBLCategory { get; set; }
    }
}
